### PR TITLE
Add two independent trip memories (A and B) 

### PR DESCRIPTION
**Pull request by Kenny-54**
with time, distance, average speed and max speed, saved in EEPROM

### CODE REVIEW

**Comment by casainho** [comment]
Thanks!! I will give a look and test on the next weekend.

**Comment by casainho** [comment]
Thank you!!

**Comment by Kenny-54** [comment]
Thanks to you too ! I'll make a PR in a few weeks when I'll fix the bad distance calculation for trip memories.

**Comment by casainho** [comment]
Thanks.

And I understand it may be hard to implement, but the reset should be from main screen.
Also, A should have an option to automatically reset everytime system start, just like previous was and that you changed.

**Comment by Kenny-54** [comment]
I'll try to add implement reset from main screen, sure it'll be more user friendly. 
Same for auto reset, I'll implement it soon. 
I did change the startup reset ? It was not my intention, I didn't want to change what it was already done.

**Pull request merged**
