### PR TITLE
Made it compile again

### PR DESCRIPTION
**Pull request by lowPerformer**
@casainho @geeksville 

+ Adding #ifndef to mainscreen.c for not (yet) implemented functions
+ Some changes in rtc.c to reflect changes done to rtc.h

### CODE REVIEW

**Comment by lowPerformer** [comment]
This PR was made before some major changes in 850C branch. I will do a new one...

**Comment by casainho** [comment]
Sorry. You can accept the PR by yourself, right?

**Comment by lowPerformer** [comment]
I could do so but a PR is done so other Devs can double check it.

**Comment by casainho** [comment]
Well, I am not being using PRs because I am currently the only one developing for 850C. And I try to communicate/ask questions on gitter.

I fell that doing a PR and waiting would be a HUGE delay and issue when I am developing.

What do you think? For instance, for SW102 you are currently the only one developing for it, since the other developer is on holidays, so, I guess you don´t need PR.

**Pull request closed without merging**
